# backend/api/routers/chat.py
"""
POST /v1/chat      — Send a message, get AI response + lender results
GET  /v1/chat/history — Load recent messages for a session
"""
from __future__ import annotations

import logging
import uuid
from typing import Any, Optional

import asyncpg
from fastapi import APIRouter, Depends, HTTPException, Query, Request
from pydantic import BaseModel, Field

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.auth import get_current_user
from core.config import cfg
from core.gemini import get_gemini_client
from core.constants import VALID_LOAN_TYPES, VALID_COMPANY_TYPES, VALID_AUM_CATEGORIES
from dependencies import get_db
from limiter import limiter

router = APIRouter()
logger = logging.getLogger(__name__)

ALLOWED_SORT_COLS = {
    "aum_crores", "established_year", "employee_count",
    "branch_count", "quality_score", "company_name",
}


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class HistoryMessage(BaseModel):
    role:    str  # "user" | "assistant"
    content: str


class ChatRequest(BaseModel):
    message:    str       = Field(..., min_length=1, max_length=1000)
    session_id: str       = Field(..., description="UUID generated by frontend")
    history:    list[HistoryMessage] = Field(default_factory=list)


class LenderResult(BaseModel):
    id:                    int
    company_name:          str
    company_type:          str
    rbi_category:          Optional[str] = None
    aum_crores:            Optional[float] = None
    aum_category:          Optional[str] = None
    hq_state:              Optional[str] = None
    hq_location:           Optional[str] = None
    pan_india:             bool = False
    primary_loan_segments: list[str] = Field(default_factory=list)
    operating_states:      list[str] = Field(default_factory=list)
    website:               Optional[str] = None
    quality_score:         Optional[float] = None
    employee_count:        Optional[int] = None
    established_year:      Optional[int] = None
    is_listed:             bool = False
    phone:                 Optional[str] = None
    email:                 Optional[str] = None


class ChatResponse(BaseModel):
    answer:          str
    intent:          str
    lenders:         list[LenderResult] = Field(default_factory=list)
    applied_filters: Optional[dict] = None
    session_id:      str


class HistoryResponse(BaseModel):
    session_id: str
    messages:   list[dict]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_arr(val: Any) -> list:
    import json as _json
    if val is None:
        return []
    if isinstance(val, list):
        return val
    try:
        return _json.loads(val)
    except Exception:
        return []


def _row_to_lender(row: Any) -> LenderResult:
    d = dict(row)
    return LenderResult(
        id=d["id"],
        company_name=d["company_name"],
        company_type=d["company_type"],
        rbi_category=d.get("rbi_category"),
        aum_crores=d.get("aum_crores"),
        aum_category=d.get("aum_category"),
        hq_state=d.get("hq_state"),
        hq_location=d.get("hq_location"),
        pan_india=bool(d.get("pan_india", False)),
        primary_loan_segments=_parse_arr(d.get("primary_loan_segments")),
        operating_states=_parse_arr(d.get("operating_states")),
        website=d.get("website"),
        quality_score=d.get("quality_score"),
        employee_count=d.get("employee_count"),
        established_year=d.get("established_year"),
        is_listed=bool(d.get("is_listed", False)),
        phone=d.get("phone"),
        email=d.get("email"),
    )


async def _search_lenders(db: asyncpg.Pool, filters: dict) -> list[LenderResult]:
    conditions = ["approval_status = 'approved'"]
    params: list = []
    idx = 1

    q = (filters.get("q") or "").strip()
    if q:
        q_esc = q.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
        conditions.append(f"company_name ILIKE ${idx}")
        params.append(f"%{q_esc}%")
        idx += 1

    company_type = [t for t in (filters.get("company_type") or []) if t in VALID_COMPANY_TYPES]
    if company_type:
        conditions.append(f"company_type = ANY(${idx}::text[])")
        params.append(company_type)
        idx += 1

    state = filters.get("state")
    if state:
        conditions.append(f"(pan_india = true OR ${idx} = ANY(operating_states))")
        params.append(state)
        idx += 1

    loan_type = [t for t in (filters.get("loan_type") or []) if t in VALID_LOAN_TYPES]
    if loan_type:
        lt_conds = []
        for lt in loan_type:
            lt_conds.append(f"${idx} = ANY(primary_loan_segments)")
            params.append(lt)
            idx += 1
        conditions.append(f"({' OR '.join(lt_conds)})")

    aum_category = [t for t in (filters.get("aum_category") or []) if t in VALID_AUM_CATEGORIES]
    if aum_category:
        conditions.append(f"aum_category = ANY(${idx}::text[])")
        params.append(aum_category)
        idx += 1

    if filters.get("aum_min") is not None:
        conditions.append(f"aum_crores >= ${idx}")
        params.append(float(filters["aum_min"]))
        idx += 1

    if filters.get("aum_max") is not None:
        conditions.append(f"aum_crores <= ${idx}")
        params.append(float(filters["aum_max"]))
        idx += 1

    if filters.get("pan_india") is not None:
        conditions.append(f"pan_india = ${idx}")
        params.append(bool(filters["pan_india"]))
        idx += 1

    if filters.get("is_listed") is not None:
        conditions.append(f"is_listed = ${idx}")
        params.append(bool(filters["is_listed"]))
        idx += 1

    sort_by = filters.get("sort_by", "aum_crores")
    if sort_by not in ALLOWED_SORT_COLS:
        sort_by = "aum_crores"
    sort_dir = "DESC" if filters.get("sort_dir", "desc") == "desc" else "ASC"

    where = " AND ".join(conditions)
    async with db.acquire() as conn:
        rows = await conn.fetch(
            f"""
            SELECT id, company_name, company_type, rbi_category,
                   aum_crores, aum_category, hq_state, hq_location,
                   pan_india, primary_loan_segments, operating_states,
                   website, quality_score, employee_count,
                   established_year, is_listed, phone, email
            FROM lenders
            WHERE {where}
            ORDER BY {sort_by} {sort_dir} NULLS LAST
            LIMIT 20
            """,
            *params,
        )
    return [_row_to_lender(r) for r in rows]


async def _fetch_lenders_by_name(db: asyncpg.Pool, names: list[str]) -> list[LenderResult]:
    results: list[LenderResult] = []
    async with db.acquire() as conn:
        for name in names[:3]:
            name_esc = name.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
            row = await conn.fetchrow(
                """
                SELECT id, company_name, company_type, rbi_category,
                       aum_crores, aum_category, hq_state, hq_location,
                       pan_india, primary_loan_segments, operating_states,
                       website, quality_score, employee_count,
                       established_year, is_listed, phone, email
                FROM lenders
                WHERE company_name ILIKE $1 AND approval_status = 'approved'
                ORDER BY quality_score DESC NULLS LAST
                LIMIT 1
                """,
                f"%{name_esc}%",
            )
            if row:
                results.append(_row_to_lender(row))
    return results


async def _ensure_session(db: asyncpg.Pool, session_id: str, user_id: str) -> None:
    async with db.acquire() as conn:
        await conn.execute(
            """
            INSERT INTO chat_sessions (id, user_id)
            VALUES ($1::uuid, $2::uuid)
            ON CONFLICT (id) DO UPDATE SET last_active = now()
            """,
            session_id, user_id,
        )


async def _save_turn(
    db: asyncpg.Pool,
    session_id: str,
    user_msg: str,
    assistant_msg: str,
    intent: str,
    filters_used: Optional[dict],
) -> None:
    import json as _json
    async with db.acquire() as conn:
        await conn.execute(
            "INSERT INTO chat_messages (session_id, role, content) VALUES ($1::uuid, 'user', $2)",
            session_id, user_msg,
        )
        await conn.execute(
            """
            INSERT INTO chat_messages (session_id, role, content, intent, filters_used)
            VALUES ($1::uuid, 'assistant', $2, $3, $4::jsonb)
            """,
            session_id, assistant_msg, intent,
            _json.dumps(filters_used) if filters_used else None,
        )


def _format_history_for_gemini(history: list[HistoryMessage], max_turns: int) -> list[dict]:
    recent = history[-(max_turns * 2):]
    return [
        {
            "role": "user" if m.role == "user" else "model",
            "parts": [m.content],
        }
        for m in recent
    ]


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("", response_model=ChatResponse)
@limiter.limit("10/minute")
async def chat(
    request: Request,
    body: ChatRequest,
    db: asyncpg.Pool = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    user_id = user.get("sub", "")
    if not user_id:
        raise HTTPException(status_code=401, detail="Invalid user token")

    try:
        uuid.UUID(body.session_id)
    except ValueError:
        raise HTTPException(status_code=422, detail="session_id must be a valid UUID")

    try:
        await _ensure_session(db, body.session_id, user_id)
    except Exception as exc:
        logger.error("chat: session upsert failed: %s", exc)
        raise HTTPException(status_code=503, detail="Service temporarily unavailable")

    gemini_history = _format_history_for_gemini(body.history, cfg.chat_context_turns)
    try:
        client = get_gemini_client()
        parsed = client.parse_response(body.message, gemini_history)
    except ValueError as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    except Exception as exc:
        logger.error("chat: Gemini error: %s", exc)
        raise HTTPException(status_code=503, detail="AI service temporarily unavailable")

    intent  = parsed.get("intent", "qa")
    answer  = parsed.get("answer", "")
    filters = parsed.get("filters") or {}
    compare_names = parsed.get("compare_names") or []

    lenders: list[LenderResult] = []
    applied_filters: Optional[dict] = None

    try:
        if intent == "filter" and filters:
            lenders = await _search_lenders(db, filters)
            applied_filters = filters
        elif intent == "compare" and compare_names:
            lenders = await _fetch_lenders_by_name(db, compare_names)
    except Exception as exc:
        logger.error("chat: DB query failed: %s", exc)
        raise HTTPException(status_code=503, detail="Search temporarily unavailable")

    try:
        await _save_turn(db, body.session_id, body.message, answer, intent, applied_filters)
    except Exception as exc:
        logger.warning("chat: failed to save turn: %s", exc)

    return ChatResponse(
        answer=answer,
        intent=intent,
        lenders=lenders,
        applied_filters=applied_filters,
        session_id=body.session_id,
    )


@router.get("/history", response_model=HistoryResponse)
@limiter.limit("30/minute")
async def get_history(
    request: Request,
    session_id: Optional[str] = Query(None),
    db: asyncpg.Pool = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    user_id = user.get("sub", "")
    if not user_id:
        raise HTTPException(status_code=401, detail="Invalid user token")

    try:
        async with db.acquire() as conn:
            if session_id:
                try:
                    uuid.UUID(session_id)
                except ValueError:
                    raise HTTPException(status_code=422, detail="session_id must be a valid UUID")
                owner = await conn.fetchval(
                    "SELECT user_id FROM chat_sessions WHERE id = $1::uuid",
                    session_id,
                )
                if str(owner) != user_id:
                    raise HTTPException(status_code=404, detail="Session not found")
                sid = session_id
            else:
                sid = await conn.fetchval(
                    "SELECT id FROM chat_sessions WHERE user_id = $1::uuid ORDER BY last_active DESC LIMIT 1",
                    user_id,
                )
                if not sid:
                    return HistoryResponse(session_id="", messages=[])

            rows = await conn.fetch(
                """
                SELECT role, content, intent, filters_used, created_at
                FROM chat_messages
                WHERE session_id = $1::uuid
                ORDER BY created_at ASC
                LIMIT $2
                """,
                str(sid), cfg.chat_history_limit,
            )
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("get_history: DB error: %s", exc)
        raise HTTPException(status_code=503, detail="History service temporarily unavailable")

    messages = [
        {
            "role":         r["role"],
            "content":      r["content"],
            "intent":       r["intent"],
            "filters_used": r["filters_used"],
            "created_at":   r["created_at"].isoformat(),
        }
        for r in rows
    ]
    return HistoryResponse(session_id=str(sid), messages=messages)
